name: Publish Docker Image

on:
  release:
    types: [ published ]
  schedule:
    - cron: '0 3 * * 3'
  workflow_dispatch:

jobs:
  push_debian:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      max-parallel: 1
      matrix:
        file:
          - Dockerfile.apline
          - Dockerfile.apline
          - Dockerfile.debian-based
          - Dockerfile.debian-based
          - Dockerfile.debian-based
          - Dockerfile.debian-based
          - Dockerfile.debian-based
          - Dockerfile.debian-based
        base:
          - alpine:3.22
          - alpine:3.23
          - debian:bookworm
          - debian:bookworm-slim
          - debian:trixie
          - debian:trixie-slim
          - ubuntu:jammy
          - ubuntu:noble
        tags:
          - "alpine-3.22"
          - "alpine,alpine-3.23,alpine-latest"
          - "debian-bookworm,debian-12"
          - "debian-bookworm-slim,debian-12-slim"
          - "debian,debian-trixie,debian-latest,debian-13"
          - "debian-slim,debian-trixie-slim,debian-latest-slim,debian-13-slim"
          - "ubuntu-jammy,ubuntu-22"
          - "ubuntu-noble,ubuntu-24"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set correct base image
        run: |
          sed -i "s/.*FROM.*/FROM ${{ matrix.base }}/" "${{ matrix.file }}"

      - name: Print Dockerfile
        run: cat "${{ matrix.file }}"

      - name: Set correct tags
        run: |
          echo "PRODUCED_TAGS=$(echo '{{ matrix.tags }}' | awk -F ',' -v OFS=',' -vdocker='dantes2104/linstor-server-docker' -vgithub='ghcr.io/edmondantes/linstor-server-docker' '{ for (i=1;i<=NF;++i) $i=docker $i"," github $i; print }')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "{{ matrix.file }}"
          platforms: linux/amd64,linux/arm64/v8,linux/riscv64
          tags: "{{ env.PRODUCED_TAGS }}"